# Generated by Django 5.0.4 on 2024-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
                ('oemModel', models.TextField()),
                ('yearModel', models.IntegerField(max_length=4)),
                ('origin', models.CharField(max_length=50)),
            ],
        ),
    ]
